apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
  labels:
    app: elastic-agent
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: elastic-agent
    {{- include "elasticsearch-agent-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: elastic-agent
      {{- include "elasticsearch-agent-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: FLEET_ENROLL
          value: {{ quote .Values.elasticAgent.elasticAgent.env.fleetEnroll }}
        - name: FLEET_INSECURE
          value: {{ quote .Values.elasticAgent.elasticAgent.env.fleetInsecure }}
        - name: FLEET_URL
          value: {{ quote .Values.elasticAgent.elasticAgent.env.fleetUrl }}
        - name: FLEET_ENROLLMENT_TOKEN
          value: {{ quote .Values.elasticAgent.elasticAgent.env.fleetEnrollmentToken }}
        - name: KIBANA_HOST
          value: {{ quote .Values.elasticAgent.elasticAgent.env.kibanaHost }}
        - name: KIBANA_FLEET_USERNAME
          value: {{ quote .Values.elasticAgent.elasticAgent.env.kibanaFleetUsername }}
        - name: KIBANA_FLEET_PASSWORD
          value: {{ quote .Values.elasticAgent.elasticAgent.env.kibanaFleetPassword }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ELASTIC_NETINFO
          value: {{ quote .Values.elasticAgent.elasticAgent.env.elasticNetinfo }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.elasticAgent.elasticAgent.image.repository }}:{{ .Values.elasticAgent.elasticAgent.image.tag
          | default .Chart.AppVersion }}
        name: elastic-agent
        resources: {{- toYaml .Values.elasticAgent.elasticAgent.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.elasticAgent.elasticAgent.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /hostfs/proc
          name: proc
          readOnly: true
        - mountPath: /hostfs/sys/fs/cgroup
          name: cgroup
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /hostfs/etc
          name: etc-full
          readOnly: true
        - mountPath: /hostfs/var/lib
          name: var-lib
          readOnly: true
        - mountPath: /etc/machine-id
          name: etc-mid
          readOnly: true
        - mountPath: /sys/kernel/debug
          name: sys-kernel-debug
        - mountPath: /usr/share/elastic-agent/state
          name: elastic-agent-state
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      serviceAccountName: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroup
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /etc
        name: etc-full
      - hostPath:
          path: /var/lib
        name: var-lib
      - hostPath:
          path: /etc/machine-id
          type: File
        name: etc-mid
      - hostPath:
          path: /sys/kernel/debug
        name: sys-kernel-debug
      - hostPath:
          path: /var/lib/elastic-agent-managed/kube-system/state
          type: DirectoryOrCreate
        name: elastic-agent-state
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
  labels:
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent'
subjects:
- kind: ServiceAccount
  name: '{{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
  labels:
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent'
subjects:
- kind: ServiceAccount
  name: '{{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-kubeadm-config
  labels:
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "elasticsearch-agent-chart.fullname" . }}-kubeadm-config'
subjects:
- kind: ServiceAccount
  name: '{{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
  labels:
    k8s-app: elastic-agent
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - events
  - pods
  - services
  - configmaps
  - serviceaccounts
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
  labels:
    k8s-app: elastic-agent
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-kubeadm-config
  labels:
    k8s-app: elastic-agent
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch-agent-chart.fullname" . }}-elastic-agent
  labels:
    k8s-app: elastic-agent
  {{- include "elasticsearch-agent-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.elasticAgent.serviceAccount.annotations | nindent 4 }}